import { Component } from '@angular/core';
import { RestService } from '../../services/rest/rest.service';
import { Router } from '@angular/router';
import { ServicioRutService } from '../../services/servicioRut/servicioRut.service';
import { Prueba2 } from '../../classes/prueba2';
import { HttpResponse } from '@angular/common/http';
import { tap } from 'rxjs/operators/tap';
/**
* This class represents the main application component.
*/
@Component({
    moduleId: module.id,
    selector: 'sd-prueba2',
    templateUrl: 'prueba2.component.html',
    styleUrls: ['prueba2.component.css'],
})
export class Prueba2Component {
    vyf1: string;
    vyf2: string;
    vyf3: string;
    vyf4: string;
    vyf5: string;
    vyf6: string;
    vyf7: string;
    vyf8: string;
    vyf9: string;
    vyf10: string;
    vyf11: string;
    vyf12: string;
    vyf13: string;
    vyf14: string;
    vyf15: string;
    primeraPartePregunta1: string;
    primeraPartePregunta2: string;
    primeraPartePregunta3: string;
    primeraPartePregunta4: string;
    primeraPartePregunta5: string;
    primeraPartePregunta6: string;
    primeraPartePregunta7: string;
    primeraPartePregunta8: string;
    primeraPartePregunta9: string;
    primeraPartePregunta10: string;
    primeraPartePregunta11: string;
    primeraPartePregunta12: string;
    primeraPartePregunta13: string;
    primeraPartePregunta14: string;
    primeraPartePregunta15: string;
    primeraPartePregunta16: string;
    primeraPartePregunta17: string;
    primeraPartePregunta18: string;
    primeraPartePregunta19: string;
    primeraPartePregunta20: string;
    primeraPartePregunta21: string;
    primeraPartePregunta22: string;
    primeraPartePregunta23: string;
    selector1: string;
    selector2: string;
    selector3: string;
    selector4: string;
    selector5: string;
    selector6: string;
    selector7: string;
    selector8: string;
    selector9: string;
    selector10: string;
    selector11: string;
    selector12: string;
    selector13: string;
    selector14: string;
    selector15: string;
    selector16: string;
    selector17: string;
    selector18: string;
    selector19: string;
    selector20: string;
    selector21: string;
    selector22: string;
    selector23: string;
    selector24: string;
    selector25: string;
    selector26: string;
    selector27: string;
    selector28: string;
    selector29: string;
    selector30: string;
    selector31: string;
    selector32: string;
    selector33: string;
    selector34: string;
    selector35: string;
    segundaPartePregunta1: string;
    segundaPartePregunta2: string;
    segundaPartePregunta3: string;
    segundaPartePregunta4: string;
    segundaPartePregunta5: string;
    segundaPartePregunta6: string;
    segundaPartePregunta7: string;
    segundaPartePregunta8: string;
    segundaPartePregunta9: string;
    segundaPartePregunta10: string;
    segundaPartePregunta12: string;
    segundaPartePregunta13: string;
    segundaPartePregunta14: string;
    segundaPartePregunta15: string;
    segundaPartePregunta16: string;
    segundaPartePregunta17: string;
    segundaPartePregunta18: string;
    segundaPartePregunta19: string;
    segundaPartePregunta20: string;
    segundaPartePregunta21: string;
    segundaPartePregunta22: string;
    segundaParteSelector1: string;
    segundaParteSelector2: string;
    segundaParteSelector3: string;
    segundaParteSelector4: string;
    prueba2: Prueba2;
    private tiempoInicio: any = performance.now();
    private tiempoFin: any;
    constructor(private rest: RestService, private router: Router, private servicioRut: ServicioRutService) {
        this.prueba2 = new Prueba2();
        this.primeraPartePregunta1 = '';
        this.primeraPartePregunta2 = '';
        this.primeraPartePregunta3 = '';
        this.primeraPartePregunta4 = '';
        this.primeraPartePregunta5 = '';
        this.primeraPartePregunta6 = '';
        this.primeraPartePregunta7 = '';
        this.primeraPartePregunta8 = '';
        this.primeraPartePregunta9 = '';
        this.primeraPartePregunta10 = '';
        this.primeraPartePregunta11 = '';
        this.primeraPartePregunta12 = '';
        this.primeraPartePregunta13 = '';
        this.primeraPartePregunta14 = '';
        this.primeraPartePregunta15 = '';
        this.primeraPartePregunta16 = '';
        this.primeraPartePregunta17 = '';
        this.primeraPartePregunta18 = '';
        this.primeraPartePregunta19 = '';
        this.primeraPartePregunta20 = '';
        this.primeraPartePregunta21 = '';
        this.primeraPartePregunta22 = '';
        this.primeraPartePregunta23 = '';
        this.vyf1 = '';
        this.vyf2 = '';
        this.vyf3 = '';
        this.vyf4 = '';
        this.vyf5 = '';
        this.vyf6 = '';
        this.vyf7 = '';
        this.vyf8 = '';
        this.vyf9 = '';
        this.vyf10 = '';
        this.vyf11 = '';
        this.vyf12 = '';
        this.vyf13 = '';
        this.vyf14 = '';
        this.vyf15 = '';
        this.selector1 = '-1';
        this.selector2 = '-1';
        this.selector3 = '-1';
        this.selector4 = '-1';
        this.selector5 = '-1';
        this.selector6 = '-1';
        this.selector7 = '-1';
        this.selector8 = '-1';
        this.selector9 = '-1';
        this.selector10 = '-1';
        this.selector11 = '-1';
        this.selector12 = '-1';
        this.selector13 = '-1';
        this.selector14 = '-1';
        this.selector15 = '-1';
        this.selector16 = '-1';
        this.selector17 = '-1';
        this.selector18 = '-1';
        this.selector19 = '-1';
        this.selector20 = '-1';
        this.selector21 = '-1';
        this.selector22 = '-1';
        this.selector23 = '-1';
        this.selector24 = '-1';
        this.selector25 = '-1';
        this.selector26 = '-1';
        this.selector27 = '-1';
        this.selector28 = '-1';
        this.selector29 = '-1';
        this.selector30 = '-1';
        this.selector31 = '-1';
        this.selector32 = '-1';
        this.selector33 = '-1';
        this.selector34 = '-1';
        this.selector35 = '-1';
        this.segundaPartePregunta1 = '';
        this.segundaPartePregunta2 = '';
        this.segundaPartePregunta3 = '';
        this.segundaPartePregunta4 = '';
        this.segundaPartePregunta5 = '';
        this.segundaPartePregunta6 = '';
        this.segundaPartePregunta7 = '';
        this.segundaPartePregunta8 = '';
        this.segundaPartePregunta9 = '';
        this.segundaPartePregunta10= '';
        this.segundaPartePregunta12 = '';
        this.segundaPartePregunta13 = '';
        this.segundaPartePregunta14 = '';
        this.segundaPartePregunta15 = '';
        this.segundaPartePregunta16 = '';
        this.segundaPartePregunta17 = '';
        this.segundaPartePregunta18 = '';
        this.segundaPartePregunta19 = '';
        this.segundaPartePregunta20 = '';
        this.segundaPartePregunta21 = '';
        this.segundaPartePregunta22 = '';
        this.segundaParteSelector1 = '-1';
        this.segundaParteSelector2 = '-1';
        this.segundaParteSelector3 = '-1';
        this.segundaParteSelector4 = '-1';
    }

    public finalizar() {
        this.prueba2.primeraPartePregunta1 = this.primeraPartePregunta1;
        this.prueba2.primeraPartePregunta2 = this.primeraPartePregunta2;
        this.prueba2.primeraPartePregunta3 = this.primeraPartePregunta3;
        this.prueba2.primeraPartePregunta4 = this.primeraPartePregunta4;
        this.prueba2.primeraPartePregunta5 = this.primeraPartePregunta5;
        this.prueba2.primeraPartePregunta6 = this.primeraPartePregunta6;
        this.prueba2.primeraPartePregunta7 = this.primeraPartePregunta7;
        this.prueba2.primeraPartePregunta8 = this.primeraPartePregunta8;
        this.prueba2.primeraPartePregunta9 = this.primeraPartePregunta9;
        this.prueba2.primeraPartePregunta10 = this.primeraPartePregunta10;
        this.prueba2.primeraPartePregunta11 = this.primeraPartePregunta11;
        this.prueba2.primeraPartePregunta12 = this.primeraPartePregunta12;
        this.prueba2.primeraPartePregunta13 = this.primeraPartePregunta13;
        this.prueba2.primeraPartePregunta14 = this.primeraPartePregunta14;
        this.prueba2.primeraPartePregunta15 = this.primeraPartePregunta15;
        this.prueba2.primeraPartePregunta16 = this.primeraPartePregunta16;
        this.prueba2.primeraPartePregunta17 = this.primeraPartePregunta17;
        this.prueba2.primeraPartePregunta18 = this.primeraPartePregunta18;
        this.prueba2.primeraPartePregunta19 = this.primeraPartePregunta19;
        this.prueba2.vyf1 = this.vyf1;
        this.prueba2.vyf2 = this.vyf2;
        this.prueba2.vyf3 = this.vyf3;
        this.prueba2.vyf4 = this.vyf4;
        this.prueba2.vyf5 = this.vyf5;
        this.prueba2.vyf6 = this.vyf6;
        this.prueba2.vyf7 = this.vyf7;
        this.prueba2.vyf8 = this.vyf8;
        this.prueba2.vyf9 = this.vyf9;
        this.prueba2.vyf10 = this.vyf10;
        this.prueba2.vyf11 = this.vyf11;
        this.prueba2.vyf12 = this.vyf12;
        this.prueba2.vyf13 = this.vyf13;
        this.prueba2.vyf14 = this.vyf14;
        this.prueba2.vyf15 = this.vyf15;
        this.prueba2.selector1 = this.selector1;
        this.prueba2.selector2 = this.selector2;
        this.prueba2.selector3 = this.selector3;
        this.prueba2.selector4 = this.selector4;
        this.prueba2.selector5 = this.selector5;
        this.prueba2.selector6 = this.selector6;
        this.prueba2.selector7 = this.selector7;
        this.prueba2.selector8 = this.selector8;
        this.prueba2.selector9 = this.selector9;
        this.prueba2.selector10 = this.selector10;
        this.prueba2.selector11 = this.selector11;
        this.prueba2.selector12 = this.selector12;
        this.prueba2.selector13 = this.selector13;
        this.prueba2.selector14 = this.selector14;
        this.prueba2.selector15 = this.selector15;
        this.prueba2.selector16 = this.selector16;
        this.prueba2.selector17 = this.selector17;
        this.prueba2.selector18 = this.selector18;
        this.prueba2.selector19 = this.selector19;
        this.prueba2.selector20 = this.selector20;
        this.prueba2.segundaPartePregunta1 = this.segundaPartePregunta1;
        this.prueba2.segundaPartePregunta2 = this.segundaPartePregunta2;
        this.prueba2.segundaPartePregunta3 = this.segundaPartePregunta3;
        this.prueba2.segundaPartePregunta4 = this.segundaPartePregunta4;
        this.prueba2.segundaPartePregunta5 = this.segundaPartePregunta5;
        this.prueba2.segundaPartePregunta6 = this.segundaPartePregunta6;
        this.prueba2.segundaPartePregunta7 = this.segundaPartePregunta7;
        this.prueba2.segundaPartePregunta8 = this.segundaPartePregunta8;
        this.prueba2.segundaPartePregunta9 = this.segundaPartePregunta9;
        this.prueba2.segundaPartePregunta10 = this.segundaPartePregunta10;
        this.prueba2.segundaPartePregunta12 = this.segundaPartePregunta12;
        this.prueba2.segundaPartePregunta13 = this.segundaPartePregunta13;
        this.prueba2.segundaPartePregunta14 = this.segundaPartePregunta14;
        this.prueba2.segundaPartePregunta15 = this.segundaPartePregunta15;
        this.prueba2.segundaPartePregunta16 = this.segundaPartePregunta16;
        this.prueba2.segundaPartePregunta17 = this.segundaPartePregunta17;
        this.prueba2.segundaPartePregunta18 = this.segundaPartePregunta18;
        this.prueba2.segundaPartePregunta19 = this.segundaPartePregunta19;
        this.prueba2.segundaPartePregunta20 = this.segundaPartePregunta20;
        this.prueba2.segundaPartePregunta21 = this.segundaPartePregunta21;
        this.prueba2.segundaPartePregunta22 = this.segundaPartePregunta22;
        this.prueba2.segundaParteSelector1 = this.segundaParteSelector1;
        this.prueba2.segundaParteSelector2 = this.segundaParteSelector2;
        this.prueba2.segundaParteSelector3 = this.segundaParteSelector3;
        this.prueba2.segundaParteSelector4 = this.segundaParteSelector4;
        this.prueba2.rut = this.servicioRut.getRutPerfil().rut;
        this.agregaPrueba().subscribe((response: HttpResponse<any>) => {
        });
    }

    public agregaPrueba() {
        this.tiempoFin = performance.now();
        let minutos = ((this.tiempoFin - this.tiempoInicio) / (1000*60)) % 60;
        this.prueba2.tiempo = minutos;
        const api = '/tesis/insertaPrueba1';
        return this.rest.post(api, this.prueba2).pipe(
            tap((response: HttpResponse<any>) => {
                if (response.status !== 200 && response.status !== 204) {
                    throw new Error(response.status.toString());
                } else {
                    if (response.status === 200) {
                        this.router.navigate(['landing']);
                    }
                }
            })
        );
    }
}

